const options = [
["See 10 minutes into the future", "See 150 years into the future"],
["Have telekinesis", "Have telepathy"],
["Team up with Wonder Woman", "Team up with Captain Marvel"],
["Be forced to sing along to", "Be forced to dance to"],
["Find true love today", "Win the lottery next year"],
["Be in jail for five years", "Be in a coma for a decade"],
["Have another 10 years with your partner", "Have a one-night stand with your celebrity crush"],
["Be chronically under-dressed", "Be overdressed"],
["Have everyone know your thoughts", "Have everyone know your Internet history"],
["Lose your sight", "Lose your memories"],
["Have universal respect", "Have unlimited power"],
["Give up air conditioning and heating", "Give up the Internet"],
["Swim in a pool of Nutella", "Swim in a pool of maple syrup"],
["Labor under a hot sun", "Labor under extreme cold"],
["Stay in during a snow day", "Build a fort during a snow day"],
["Buy 10 things you don't need", "Forget the one thing you need"],
["Never go out during the day", "Never go out at night"],
["Have a personal maid", "Have a personal chef"],
["Be 11 feet tall", "Be nine inches tall"],
["Have Beyoncé's talent", "Have Jay-Z's business acumen"],
["Be an extra in an Oscar-winning movie", "Be the lead in a box office bomb"],
["Vomit on your hero", "Have your hero vomit on you"],
["Communicate only in emoji", "Never be able to text at all ever again"],
["Be royalty 1,000 years ago", "Be an average person today"],
["Lounge by the pool", "Lounge on the beach"],
["Wear the same socks for a month", "Wear the same underwear for a week"],
["Work an overtime shift with your annoying boss", "Spend a full day with your mother-in-law"],
["Cuddle a koala", "Pal around with a panda"],
["Have a sing-off with Ariana Grande", "Have a dance-off with Rihanna"],
["Always have B.O. and not know it", "Always smell B.O. on everyone else"],
["Watch nothing but Hallmark Christmas movies", "Watch nothing but horror movies"],
["Always be 10 minutes late", "Always be 20 minutes early"],
["Spend a week in the forest", "Spend a night in a real haunted house"],
["Find a rat in your kitchen", "Find a roach in your bed"],
["Have a pause button", "Have a rewind button"],
["Have a full phone battery", "Have a full gas tank"],
["Lose all your teeth", "Lose a day of your life every time you kiss someone"],
["Drink from a toilet", "Pee in a litter box"],
["Live the same day over and over", "Take 3 years off the end of your life"],
["Never eat watermelon ever again", "Be forced to eat watermelon with every meal"],
["Get a paper cut every time you turn a page", "Bite your tongue every time you eat"],
["Oversleep every day for a week", "Not get any sleep at all for four days"],
["Die in 20 years with no regrets", "Live to 100 with a lot of regrets"],
["Sip gin with Ryan Reynolds", "Shoot tequila with Dwayne The Rock Johnson"],
["Get trapped in the middle of a food fight", "Get trapped in the middle of a water balloon fight"],
["Walk to work in heels", "Drive to work in reverse"],
["Spend a year at war", "Spend a year in prison"],
["Die before your partner", "Die after your partner"],
["Have a child every year for 20 years", "Never have any children at all"],
["Take amazing selfies but look terrible in all other photos", "Be photogenic everywhere but in your selfies"],
["Be gassy on a first date", "Be gassy on your wedding night"],
["Be played by Danny DeVito", "Be played by Danny Trejo"],
["Take back anything you say", "Hear any conversation that is about you"],
["Have skin that changes color based on your emotions", "Have tattoos appear all over your body depicting what you did yesterday"],
["Hunt and butcher your own meat", "Never eat meat again"],
["Lose all of your friends but keep your BFF", "Lose your BFF but keep the rest of your buds"],
["Have people spread a terrible lie about you", "Have people spread terrible but true tales about you"],
["Walk in on your parents", "Have your parents walk in on you"],
["Be the absolute best at something that no one takes seriously", "Be average at something well respected"],
["Have unlimited battery life on all of your devices", "Have free WiFi wherever you go"],
["Have Billie Eilish's future", "Have Madonna's legacy"],
["Have a third nipple", "Have an extra toe"],
["Solve world hunger", "Solve global warming"],
["Wear every shirt inside out", "Wear every pair of pants backward"],
["Live in a treehouse", "Live in a cave"],
["Win $25,000", "Have your best friend win $100,000"],
["Be in history books for something terrible", "Be forgotten completely after you die"],
["Travel the world for free for a year", "Have $50,000 to spend however you please"],
["Only be able to talk to your dog", "Have your dog be able to talk to only you"],
["Have a mullet for a year", "Be bald for six months"],
["Go back to the past to meet your loved ones who passed away", "Go to the future to meet your children or grandchildren"],
["Have Angelina Jolie's lips", "Have Jennifer Aniston's hair"],
["Stay the age you are physically forever", "Stay the way you are now financially forever"],
["Live through a zombie apocalypse", "Live through a robot apocalypse"],
["Be alone all your life", "Be surrounded by really annoying people"],
["Give up your cellphone for a month", "Give up bathing for a month"],
["Spend a day cleaning your worst enemy's house", "Have your crush spend the day cleaning your house"],
["Spend a year entirely alone", "Spend a year without a home"],
["Buy all used underwear", "Buy all used toothbrushes"],
["Have a photographic memory", "Have an IQ of 200"],
["Go on a cruise with your boss", "Never go on vacation ever again"],
["Forget your partner's birthday", "Forget your anniversary"],
["Have to wear stilettos to sleep", "Have to wear slippers everywhere you go"],
["Change the outcome of the last election", "Decide the outcome of the next election"],
["Lose the ability to read", "Lose the ability to speak"],
["Smooch Chris Pratt", "Smooch Chris Pine"],
["Be beautiful and stupid", "Be unattractive but a genius"],
["Have seven fingers on each hand", "Have seven toes on each foot"],
["Work the job you have now for a year at double your current rate of pay", "Have one year off with what you are making now"],
["Always be stuck in traffic but find a perfect parking spot", "Never hit traffic but always take forever to park"],
["Have super-sensitive taste buds", "Have super-sensitive hearing"],
["Ask your ex for a favor", "Ask a total stranger for a favor"],
["Go on tour with Elton John", "Go on tour with Cher"],
["Eat only pizza for a year", "Not eat any pizza for five years"],
["Never get another present but always pick the perfect present", "Keep getting presents but giving terrible ones"],
["Sleep in a doghouse", "Let stray dogs sleep in your bed"],
["Speak any language", "Communicate with animals"],
["Have all messages and photos leak publicly", "Never use a cellphone ever again"],
["Run at 100 mph", "Fly at 20 mph"],
["Have Adele's voice", "Have Normani's dance moves"],
["Always wear sweatpants", "Never wear sweatpants again"],
["Have 10,000 spoons when all you need is a knife", "Always have a knife but never be able to use spoons"],
["Detect every lie you hear", "Get away with every lie you tell"],
["Be the funniest person in a room", "Be the smartest person in a room"],
["Talk like Yoda", "Breathe like Darth Vader"],
["Have people know all the details of your finances", "Have people know all the details of your love life"],
["Listen to your least-favorite song on a loop for a year", "Never listen to any music at all for a year"],
["Go vegan for a month", "Only eat meat and dairy for a month"],
["Clean up someone else's vomit", "Clean up someone else's blood"],
["Work for Michael Scott", "Work for Mr. Burns"],
["Spend the weekend with pirates", "Spend the weekend with ninjas"],
["End every phone call with I love you", "Accidentally call your partner the wrong name during a fight"],
["Get your paycheck given to you in pennies", "Never be able to use cash again"],
["See Lady Gaga in a movie", "See Bradley Cooper in concert"],
["Win the lottery but have to spend it all in one day", "Triple your current salary forever"],
["Live until you are 200 and look your age", "Look like you're 22 your whole life", "But die at age 65"],
["Give up cursing forever", "Give up ice cream for 12 years"],
["Hear a comforting lie", "Hear an uncomfortable truth"],
["Be locked for a week in a room that's overly bright", "Be locked in a room that's totally dark"],
["Have someone see all the photos in your phone", "Have someone read all your text messages"],
["Have a South Park-themed wedding", "Have a Family Guy-themed funeral"],
["Have to hunt and gather all of your food", "Eat McDonald's for every meal"],
["Have fortune", "Have fame"],
["Celebrate the Fourth of July with Taylor Swift", "Celebrate Christmas with Mariah Carey"],
["Only be able to listen to one song for the rest of your life", "Only be able to watch one movie for the rest of your life"],
["Never use social media again", "Never watch another movie ever again"],
["Have police hunting you down for a crime you didn't commit", "Have a serial killer actually hunting you"],
["Live a peaceful life in a small cabin in the woods", "Live a drama-filled life in a mansion in a big city"],
["Find your soulmate", "Find your calling"],
["Drink sour milk", "Brush your teeth with soap"],
["Steal Duchess Meghan's style", "Steal Duchess Kate's style"],
["Never get a cold ever again", "Never be stuck in traffic ever again"],
["Be tall and average looking", "Be three feet tall but beautiful"],
["Visit the International Space Station for a week", "Spend a week in a hotel at the bottom of the ocean"],
["Confess to cheating on your partner", "Catch your partner cheating on you"],
["Have all traffic lights you approach be green", "Never have to stand in line again"],
["Share an onscreen kiss with Leonardo DiCaprio", "Share an onscreen kiss with George Clooney"],
["Never eat Christmas cookies ever again", "Never eat Halloween candy ever again"],
["Lose your long-term memory", "Lose your short-term memory"],
["Have a mullet", "Have a perm"],
["Be stranded in the jungle", "Be stranded in the desert"],
["Have everyone you love forget your birthday", "Have everyone you love sing Happy Birthday to you for 24 hours straight"],
["Be invisible", "Be able to fly"],
["Spend every weekend indoors", "Spend every weekend outdoors"],
["Party with Jennifer Lopez and Alex Rodriguez", "Party with Kim Kardashian and Kanye West"],
["Give up wine for a year", "Drink nothing but wine for a year"],
["Start a colony on another planet", "Be the leader of a country on Earth"],
["Live in a house haunted by friendly ghosts", "Be a ghost reliving your average day after you die"],
["Have one wish granted today", "Have 10 wishes granted 20 years from now"],
["Get hit on by someone 20 years older than you", "Get hit on by someone 20 years younger than you"],
["Fall down in public", "Pass gas in public"],
["Only eat raw food", "Only eat TV dinners"],
["Run as fast as The Flash", "Be as strong as Superman"],
["Never have a wedgie", "Never have anything stuck in your teeth ever again"],
["Marry the most attractive person you've ever met", "Marry the best cook you've ever met"],
["Sing karaoke with Gwen Stefani", "Sing karaoke with Kelly Clarkson"],
["Go back to kindergarten with everything you know now", "Know now everything your future self will learn"],
["Be able to read minds", "Predict the future"],
["Take a pill a day for nutrients and to feel full", "But never eat anything again", "Eat whatever you want but never really feel full"],
["Be an unknown superhero", "Be an infamous villain"],
["Always have an annoying song stuck in your head", "Always have an itch that you can't reach"],
["Never be able to keep anyone else's secrets", "Have someone tell all of your secrets"],
["Be Batman", "Be Iron Man"],
["Be married to someone stunning who doesn't think you're attractive", "Be married to someone ugly who thinks you're gorgeous"],
["Have a third ear", "Have a third eye"],
["Have $1 million now", "Have $5,000 a week for the rest of your life"],
["Binge-watch Sex And the City", "Binge-watch Girls"],
["Be rich working a job you hate", "Be poor working a job you love"],
["Wear real fur", "Wear fake jewels"],
["Work a high-paying job that you hate", "Work your dream job with only just enough money for rent", "Food and utilities"],
["Wake up naked in a forest five miles from home", "Wake up in your underwear at work"],
["Go backstage with your favorite band", "Be an extra on your favorite TV show"],
["Never eat your favorite food for the rest of your life", "Only eat your favorite food"],
["Be able to erase your own memories", "Be able to erase someone else's memories"],
["Be so afraid of heights that you can’t go to the second floor of a building", "Be so afraid of the sun that you can only leave the house on rainy days"],
["Have a rap battle against Nicki Minaj", "Have a rap battle against Lizzo"],
["Save your best friend's life if it meant five strangers would die", "Save five strangers if it meant sacrificing your best friend"],
["Give up coffee", "Give up soda forever"],
["Find a $100 bill floating in a public toilet", "Find a $20 bill in your own pocket"],
["Wear nothing but neon orange", "Wear nothing but neon green for an entire year"],
["Eat the same thing for every meal for a year", "Be able to eat whatever you wanted", "But only once every three days"],
["Get drunk off of one sip of alcohol", "Never get drunk no matter how much booze you imbibe"],
["Sell all of your possessions", "Sell one of your organs"],
["Clean a toilet with your toothbrush", "Clean a floor with your tongue"],
["Be asked the same question over and over again", "Never be spoken to ever again"],
["Be reincarnated as a fly", "Just stop existing when you die"],
["Be serenaded by Justin Bieber", "Be serenaded by Justin Timberlake"],
["Be unable to close any door once it's open", "Be unable to open any door once it's closed"],
["Throw the best parties but have to clean up the mess by yourself", "Never go to a party again"],
["Have a tattoo of the title of the last book you read", "Have a tattoo of the last TV show you watched"],
["Wear clothes that were always way too big", "Wear clothes a couple sizes too small"],
["Give your parents access to your browser history", "Give your boss access to your browser history"],
["Only be able to wash your hair twice a year", "Only be able to check your phone once a day"],
["Have a tennis lesson from Serena Williams", "Have a soccer lesson from Meghan Rapinoe"],
["Have a permanent unibrow", "Have no eyebrows at all"],
["Have aliens be real and covered up by the government", "Have no extraterrestrial life at all in the universe"],
["Be caught liking your ex's Instagram pics", "Be caught liking your partner's ex's Instagram pics"],
["Never eat cookies ever again", "Only ever drink water"],
["Donate your organs to those who need them", "Donate your entire body to science"],
["Be criticized", "Be ignored"],
["Work alongside Dwight Schrute", "Work alongside Homer Simpson"],
["Be punished for a crime you didn't commit", "Have someone else take credit for one of your major accomplishments"],
["Eat an undercooked meal", "Eat a burnt meal"],
["Get a cooking lesson from Gordon Ramsay", "Get a cooking lesson from Ina Garten"],
["Have your boss look through your text messages", "Have your parents look through your text messages"],
["Have your first child when you're 18", "Have your first child when you're 50"],
["Star in a Star Wars film", "Star in a Marvel film"],
["Wear heels to the gym", "Wear sneakers to a wedding"],
["Give up brushing your hair", "Give up brushing your teeth"],
["Master every musical instrument", "Master every type of sport"],
["Always have wet socks", "Have a small rock in your shoe"],
["Have Celine Dion perform the soundtrack to your life", "Have Eminem perform the soundtrack to your life"],
["Be the class clown", "Be the teacher's pet"],
["Bathe in the dishwater", "Wash dishes in your bathwater"],
["Show up to a job interview with stained pants", "Show up to a job interview with pit stains"],
["Never age physically", "Never age mentally"],
["Date someone with bad breath", "Date someone with bad manners"],
["Never wear makeup ever again", "Wear a full face of the wrong shades every day"],
["Read the book", "Watch the movie"],
["Have a slumber party with Anna Kendrick", "Go to a comedy show with Rebel Wilson"],
["Eat chocolate on pizza", "Never eat chocolate ever again"],
["Have X-ray vision of people you find unattractive", "Have everyone else have X-ray vision of you"],
["Have your own theme park", "Have your own zoo"],
["Be the star player on a losing team", "Warm the bench on a championship roster"],
["Know when you're going to die", "Know how you're going to die"],
["Lose all of your teeth", "Lose all of your hair"],
["Watch nothing but The Office", "Watch nothing but Friends"],
["Lose your keys", "Lose your phone"],
["Live in a home with no electricity", "Live in a home with no running water"],
["Be rich with no friends", "Be poor and popular"],
["Look strong and be weak", "Look weak and be strong"],
["Have your style critiqued by Anna Wintour", "Have your style critiqued by Miranda Priestly"],
["Wear one color everyday", "Wear seven colors everyday"],
["Sneeze nonstop for 15 minutes once every day", "Sneeze once every three minutes of the day while you're awake"],
["Walk barefoot in a public bathroom", "Walk through poison ivy"],
["Have the ability to see 10 years into your own future", "Have the ability to see six months into the future of the world"],
["Have nobody remember who you are at your 20-year class reunion", "Have everybody comment on how old you look"],
["Shoot hoops with LeBron James", "Toss a football with Tom Brady"],
["Live through an episode of Orange Is The New Black", "Live through an episode of Black Mirror"],
["Only be able to listen to Christmas songs all year round", "Only be able to watch nothing but horror movies"],
["Be a genius everyone thinks is an idiot", "Be an idiot everyone thinks is a genius"],
["Win on Survivor", "Win on The Bachelor or The Bachelorette"],
["Be beloved by the general public but your family and friends hate you", "Be hated by the general public but your family and friends love you"],
["Be color blind", "Lose your sense of taste"],
["Live on a desert island with your celebrity crush", "Live in a mansion with your ex"],
["Pass gas every time you meet someone new", "Burp every time you kiss someone"],
["Have tea with Queen Elizabeth", "Have a beer with Prince Harry"],
["Give up the Internet", "Give up showering for a month"],
["Get away with a terrible crime but live in fear of someone discovering it", "Go to prison for three years for a crime you didn't commit"],
["Be forced to live the same day over and over again for a full year", "Take three years off the end of your life"]];